### ISSUE TITLE
ERROR! no action detected in task. This often indicates a misspelled module name, or incorrect module path.

### ISSUE THREAD

**Issue by BSG83** [fortinet-solutions-cse/40ansible#20]
Hi,

When trying to run this playbook:
---
- name: Backup current config
  hosts: all

  tasks:
  - name: backup system config
    fortiosconfig:
     config: "system config backup"
     action: "backup"
     config_parameters:
      filename: "backup_config_001"

The error below is shown:
ERROR! no action detected in task. This often indicates a misspelled module name, or incorrect module path.

The error appears to have been in '/etc/ansible/clients/firewalls/fortigate-firewall.yml': line 6, column 5, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

  tasks:
  - name: backup system config
    ^ here

**Comment by chopraaa** [comment]
Check indentation:

```yaml
name: backup system config
fortiosconfig:
config: "system config backup"
action: "backup"
config_parameters:
filename: "backup_config_001"
```

should be:

```yaml
name: backup system config
fortiosconfig:
  config: "system config backup"
  action: "backup"
  config_parameters:
  filename: "backup_config_001"
```
