### ISSUE TITLE
Login failed when trying to configure web filtering

### ISSUE THREAD

**Issue by dragan979** [fortinet-solutions-cse/40ansible#26]
I need to explicitly enable HTTP on fortigate interface in order to avoid "Connection timed out" error 

```
- hosts: localhost
  vars_files:
   - /home/centos/ansible/40ansible/vars/main.yml

  gather_facts: no
  tasks:
   - name: Configure web content filtering in fortigate
     fortios_webfilter:
       host:  "{{  host }}"
       username: "{{  username}}"
       password: "{{ password }}"
       vdom:  "{{  vdom }}"
       webfilter_content:
         id: "1"
         name: "default"
         comment: ""
         entries:
           - name: "bet-online"
             pattern-type: "wildcard"
             status: "enable"
             lang: "western"
             score: 40
             action: "block"
           - name: "tv-.*online"
             pattern-type: "regexp"
             status: "enable"
             lang: "western"
             score: 42
             action: "block"
         state: "present"
```

Errors:

The full traceback is:
Traceback (most recent call last):
  File "/root/.ansible/tmp/ansible-tmp-1544708418.34-194837611454630/AnsiballZ_fortios_webfilter.py", line 113, in <module>
    _ansiballz_main()
  File "/root/.ansible/tmp/ansible-tmp-1544708418.34-194837611454630/AnsiballZ_fortios_webfilter.py", line 105, in _ansiballz_main
    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
  File "/root/.ansible/tmp/ansible-tmp-1544708418.34-194837611454630/AnsiballZ_fortios_webfilter.py", line 48, in invoke_module
    imp.load_module('__main__', mod, module, MOD_DESC)
  File "/tmp/ansible_fortios_webfilter_payload_QeJMZJ/__main__.py", line 548, in <module>
  File "/tmp/ansible_fortios_webfilter_payload_QeJMZJ/__main__.py", line 539, in main
  File "/tmp/ansible_fortios_webfilter_payload_QeJMZJ/__main__.py", line 459, in fortios_webfilter
  File "/usr/lib/python2.7/site-packages/fortiosapi/fortiosapi.py", line 127, in login
    raise Exception('login failed')
Exception: login failed

fatal: [localhost]: FAILED! => {
    "changed": false,
    "module_stderr": "Traceback (most recent call last):\n  File \"/root/.ansible/tmp/ansible-tmp-1544708418.34-194837611454630/AnsiballZ_fortios_webfilter.py\", line 113, in <module>\n    _ansiballz_main()\n  File \"/root/.ansible/tmp/ansible-tmp-1544708418.34-194837611454630/AnsiballZ_fortios_webfilter.py\", line 105, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/root/.ansible/tmp/ansible-tmp-1544708418.34-194837611454630/AnsiballZ_fortios_webfilter.py\", line 48, in invoke_module\n    imp.load_module('__main__', mod, module, MOD_DESC)\n  File \"/tmp/ansible_fortios_webfilter_payload_QeJMZJ/__main__.py\", line 548, in <module>\n  File \"/tmp/ansible_fortios_webfilter_payload_QeJMZJ/__main__.py\", line 539, in main\n  File \"/tmp/ansible_fortios_webfilter_payload_QeJMZJ/__main__.py\", line 459, in fortios_webfilter\n  File \"/usr/lib/python2.7/site-packages/fortiosapi/fortiosapi.py\", line 127, in login\n    raise Exception('login failed')\nException: login failed\n",
    "module_stdout": "",
    "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error",
    "rc": 1
}

CentOS 7

ansible 2.7.4
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /bin/ansible
  python version = 2.7.5 (default, Oct 30 2018, 23:45:53) [GCC 4.8.5 20150623 (Red Hat 4.8.5-36)]

**Comment by mamunozgonzalez** [comment]
Hi @dragan979,
 I just tested your example on a brand new fortigate vm 6.0.2 and it works perfectly. The only thing that I changed was the variables. I used exactly this playbook and it worked fine:

```
- hosts: localhost
  vars:
   host: "192.168.122.40"
   username: "admin"
   password: ""
   vdom: "root"
  gather_facts: no
  tasks:
   - name: Configure web content filtering in fortigate
     fortios_webfilter:
       host:  "{{  host }}"
       username: "{{  username}}"
       password: "{{ password }}"
       vdom:  "{{  vdom }}"
       webfilter_content:
         id: "1"
         name: "default"
         comment: ""
         entries:
           - name: "bet-online"
             pattern-type: "wildcard"
             status: "enable"
             lang: "western"
             score: 40
             action: "block"
           - name: "tv-.*online"
             pattern-type: "regexp"
             status: "enable"
             lang: "western"
             score: 42
             action: "block"
         state: "present"
```
Can you use this file as it is (puting credentials on it)? Please ensure the credentials are ok. I don't see any other problem in your traceback than the one related to a bad login. Please note that old fgt versions may not be supported.

Regarding HTTPS, this module only supports HTTP but we are adding HTTPS feature gradually to every module, as you can see in https://github.com/fortinet-solutions-cse/ansible_fgt_modules

Feel free to give it a try to:  
https://github.com/fortinet-solutions-cse/ansible_fgt_modules/blob/master/v6.0.2/webfilter/fortios_webfilter_content.py
(and use https if desired)
