### ISSUE TITLE
Is it possible to perform a rename action?

### ISSUE THREAD

**Issue by JonTheNiceGuy** [fortinet-solutions-cse/40ansible#40]
I've reviewed the code of fortiosconfig.py and the ansible_fgt_modules and I can't find an example of a rename action.

From the CLI you can do

```
configure firewall address
rename hosta to hostb
end
```

Is it possible to so something like this with the API?

**Comment by mamunozgonzalez** [comment]
Hi @JonTheNiceGuy 
 At the moment this action is not supported in our Ansible modules. Fortiosconfig can be a good candidate for that operation in the future.

With API it is possible. Using a PUT call on the object as shown below will work:
/api/v2/cmdb/firewall/address/hosta?vdom=root

And then in the body data include this:
{"name": "hostb"}

It will rename hosta to hostb.
Please check also docs on https://fndn.fortinet.net

**Comment by JonTheNiceGuy** [comment]
Desired play:

```
- fortiosconfig:
    host: host1
    username: user
    password: password
    vdom: root
    action: rename
    config: firewall address
      name: hosta
      newname: hostb
```
