### ISSUE TITLE
SSL issue running fortios_firewall_adress

### ISSUE THREAD

**Issue by rdzielicki** [fortinet-solutions-cse/40ansible#53]
ISSUE TYPE

Hello,

Using Ansible via Tower, we are not able to create an object on Fortigate 240D firewall using fortios_firewall_adress module.
Playbook ends each time with same error (see below).

COMPONENT NAME
Ansible: 2.9.6
Python 3.6
FortiosAPI: 1.0.1
Ansible module : fortios_firewall_adress
Fortigate firewall is 240D running on 6.0.6
ANSIBLE VERSION

Ansible version is  2.9.6

OS / ENVIRONMENT

Tower is running on CentOS Linux release 7.7.1908
STEPS TO REPRODUCE

To reproduce you can play playbook below

---                                                                               

- hosts: localhost
  gather_facts: False
  vars:                                                                           
   host: "10.109.109.1"                                                           
   username: "fakeusername"                                                              
   password: "fakepassword"                                                          
   vdom: "root"                                                            
  tasks:                                                                          
  - name: Configure IPv4 addresses.                                               
    fortios_firewall_address:                                                     
      host:  "{{ host }}"                                                         
      username: "{{ username }}"                                                  
      password: "{{ password }}"                                                  
      vdom:  "{{ vdom }}"                                                         
      state: "present"                                                            
      firewall_address:                                                           
        name: "TOWER_TEST"                                                
        subnet: "1.2.3.4 255.255.255.255"
        comment: "TOWER_TEST_COMMENT"		

EXPECTED RESULTS

Object to be created in the firewall.
ACTUAL RESULTS

PLAY [localhost] ***************************************************************

TASK [fortios_tasks : CREATE OBJECT ON FORTIGATE] ******************************
fatal: [localhost]: FAILED! => {"changed": false, "module_stderr": "/opt/my-envs/Ansible2.9P3/lib/python3.6/site-packages/urllib3/connectionpool.py:1004: InsecureRequestWarning: Unverified HTTPS request is being made to host '10.109.109.1'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings\\n  InsecureRequestWarning,\\nTraceback (most recent call last):\\n  File \\"/var/lib/awx/.ansible/tmp/ansible-tmp-1586426295.6123304-22106732036127/AnsiballZ_fortios_firewall_address.py\\", line 102, in <module>\\n    _ansiballz_main()\\n  File \\"/var/lib/awx/.ansible/tmp/ansible-tmp-1586426295.6123304-22106732036127/AnsiballZ_fortios_firewall_address.py\\", line 94, in _ansiballz_main\\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\\n  File \\"/var/lib/awx/.ansible/tmp/ansible-tmp-1586426295.6123304-22106732036127/AnsiballZ_fortios_firewall_address.py\\", line 40, in invoke_module\\n    runpy.run_module(mod_name='ansible.modules.network.fortios.fortios_firewall_address', init_globals=None, run_name='__main__', alter_sys=True)\\n  File \\"/usr/lib64/python3.6/runpy.py\\", line 205, in run_module\\n    return _run_module_code(code, init_globals, run_name, mod_spec)\\n  File \\"/usr/lib64/python3.6/runpy.py\\", line 96, in _run_module_code\\n    mod_name, mod_spec, pkg_name, script_name)\\n  File \\"/usr/lib64/python3.6/runpy.py\\", line 85, in _run_code\\n    exec(code, run_globals)\\n  File \\"/tmp/ansible_fortios_firewall_address_payload_o04mvvs_/ansible_fortios_firewall_address_payload.zip/ansible/modules/network/fortios/fortios_firewall_address.py\\", line 570, in <module>\\n  File \\"/tmp/ansible_fortios_firewall_address_payload_o04mvvs_/ansible_fortios_firewall_address_payload.zip/ansible/modules/network/fortios/fortios_firewall_address.py\\", line 560, in main\\n  File \\"/tmp/ansible_fortios_firewall_address_payload_o04mvvs_/ansible_fortios_firewall_address_payload.zip/ansible/modules/network/fortios/fortios_firewall_address.py\\", line 462, in fortios_firewall\\n  File \\"/tmp/ansible_fortios_firewall_address_payload_o04mvvs_/ansible_fortios_firewall_address_payload.zip/ansible/modules/network/fortios/fortios_firewall_address.py\\", line 445, in firewall_address\\n  File \\"/opt/my-envs/Ansible2.9P3/lib/python3.6/site-packages/fortiosapi/fortiosapi/fortiosapi.py\\", line 422, in set\\n    mkey = self.get_mkey(path, name, data, vdom=vdom)\\n  File \\"/opt/my-envs/Ansible2.9P3/lib/python3.6/site-packages/fortiosapi/fortiosapi/fortiosapi.py\\", line 233, in get_mkey\\n    keyname = self.get_mkeyname(path, name, vdom)\\n  File \\"/opt/my-envs/Ansible2.9P3/lib/python3.6/site-packages/fortiosapi/fortiosapi/fortiosapi.py\\", line 222, in get_mkeyname\\n    schema = self.schema(path, name, vdom=vdom)\\n  File \\"/opt/my-envs/Ansible2.9P3/lib/python3.6/site-packages/fortiosapi/fortiosapi/fortiosapi.py\\", line 322, in schema\\n    url = self.cmdb_url(path, name, vdom=vdom) + \\"&action=schema\\"\\n  File \\"/opt/my-envs/Ansible2.9P3/lib/python3.6/site-packages/fortiosapi/fortiosapi/fortiosapi.py\\", line 257, in cmdb_url\\n    self.check_session()\\n  File \\"/opt/my-envs/Ansible2.9P3/lib/python3.6/site-packages/fortiosapi/fortiosapi/fortiosapi.py\\", line 131, in check_session\\n    raise NotLogged()\\nfortiosapi.fortiosapi.exceptions.NotLogged: Not logged on a session, please login.\\n", "module_stdout": "", "msg": "MODULE FAILURE\\nSee stdout/stderr for the exact error", "rc": 1}
[

PLAY RECAP *********************************************************************
localhost                  : ok=0    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0

**Comment by tlrichiec** [comment]
Hi rdzielicki

Try adding 'ssl_verify: "no"' as per the following:

```
- hosts: localhost
  vars:
    host: "2.3.4.5"
    username: "someusername"
    password: "somepassword"
    vdom: "root"
  tasks:
    - name: Configure IPv4 addresses.
      fortios_firewall_address:
        host: "{{ host }}"
        username: "{{ username }}"
        password: "{{ password }}"
        vdom: "{{ vdom }}"
        state: "present"
        ssl_verify: "no"
        firewall_address:
          name: "TOWER_TEST"
          subnet: "1.2.3.4 255.255.255.255"
          comment: "TOWER_TEST_COMMENT"
```

[WARNING]: provided hosts list is empty, only localhost is available. Note that the implicit localhost does not match
'all'


PLAY [localhost] *******************************************************************************************************

TASK [Gathering Facts] *************************************************************************************************
ok: [localhost]

TASK [Configure IPv4 addresses.] ***************************************************************************************
changed: [localhost]

PLAY RECAP *************************************************************************************************************
localhost                  : ok=2    changed=1    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0

**Comment by chillancezen** [comment]
hi @rdzielicki,

you are using legacy mode.
you can using httpapi to run your playbook..
```
- hosts: fortigates
  connection: httpapi
  vars:
   vdom: "root"
   ansible_httpapi_use_ssl: yes
   ansible_httpapi_validate_certs: no
   ansible_httpapi_port: 443
  tasks:
  - name: Configure global attributes.
    fortios_system_global:
      vdom:  "{{ vdom }}"
      system_global:
        admintimeout: "23"
        hostname: "chfdafdazzeers"
```


```
#cat hosts
[fortigates]
fortigate01 ansible_host=172.22.13.10 ansible_user="admin" ansible_password="__fake__password"

[fortigates:vars]
ansible_network_os=fortios
```

thanks,
Link

**Comment by greenspartan** [comment]
Hi @tlrichiec ,

I am working with rdzieliecki; I've modified our playbook as advised adding ssl_verify: "no" param (I tried also with "False", but unfortunately I got same error :

```
{
    "module_stdout": "",
    "module_stderr": "/opt/my-envs/Ansible2.9P3/lib/python3.6/site-packages/urllib3/connectionpool.py:1004: InsecureRequestWarning: Unverified HTTPS request is being made to host '10.109.109.1'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings\n  InsecureRequestWarning,\nTraceback (most recent call last):\n  File \"/var/lib/awx/.ansible/tmp/ansible-tmp-1586841300.3641403-172249354718460/AnsiballZ_fortios_firewall_address.py\", line 102, in <module>\n    _ansiballz_main()\n  File \"/var/lib/awx/.ansible/tmp/ansible-tmp-1586841300.3641403-172249354718460/AnsiballZ_fortios_firewall_address.py\", line 94, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/var/lib/awx/.ansible/tmp/ansible-tmp-1586841300.3641403-172249354718460/AnsiballZ_fortios_firewall_address.py\", line 40, in invoke_module\n    runpy.run_module(mod_name='ansible.modules.network.fortios.fortios_firewall_address', init_globals=None, run_name='__main__', alter_sys=True)\n  File \"/usr/lib64/python3.6/runpy.py\", line 205, in run_module\n    return _run_module_code(code, init_globals, run_name, mod_spec)\n  File \"/usr/lib64/python3.6/runpy.py\", line 96, in _run_module_code\n    mod_name, mod_spec, pkg_name, script_name)\n  File \"/usr/lib64/python3.6/runpy.py\", line 85, in _run_code\n    exec(code, run_globals)\n  File \"/tmp/ansible_fortios_firewall_address_payload_3ijavzv0/ansible_fortios_firewall_address_payload.zip/ansible/modules/network/fortios/fortios_firewall_address.py\", line 570, in <module>\n  File \"/tmp/ansible_fortios_firewall_address_payload_3ijavzv0/ansible_fortios_firewall_address_payload.zip/ansible/modules/network/fortios/fortios_firewall_address.py\", line 560, in main\n  File \"/tmp/ansible_fortios_firewall_address_payload_3ijavzv0/ansible_fortios_firewall_address_payload.zip/ansible/modules/network/fortios/fortios_firewall_address.py\", line 462, in fortios_firewall\n  File \"/tmp/ansible_fortios_firewall_address_payload_3ijavzv0/ansible_fortios_firewall_address_payload.zip/ansible/modules/network/fortios/fortios_firewall_address.py\", line 445, in firewall_address\n  File \"/opt/my-envs/Ansible2.9P3/lib/python3.6/site-packages/fortiosapi/fortiosapi/fortiosapi.py\", line 422, in set\n    mkey = self.get_mkey(path, name, data, vdom=vdom)\n  File \"/opt/my-envs/Ansible2.9P3/lib/python3.6/site-packages/fortiosapi/fortiosapi/fortiosapi.py\", line 233, in get_mkey\n    keyname = self.get_mkeyname(path, name, vdom)\n  File \"/opt/my-envs/Ansible2.9P3/lib/python3.6/site-packages/fortiosapi/fortiosapi/fortiosapi.py\", line 222, in get_mkeyname\n    schema = self.schema(path, name, vdom=vdom)\n  File \"/opt/my-envs/Ansible2.9P3/lib/python3.6/site-packages/fortiosapi/fortiosapi/fortiosapi.py\", line 322, in schema\n    url = self.cmdb_url(path, name, vdom=vdom) + \"&action=schema\"\n  File \"/opt/my-envs/Ansible2.9P3/lib/python3.6/site-packages/fortiosapi/fortiosapi/fortiosapi.py\", line 257, in cmdb_url\n    self.check_session()\n  File \"/opt/my-envs/Ansible2.9P3/lib/python3.6/site-packages/fortiosapi/fortiosapi/fortiosapi.py\", line 131, in check_session\n    raise NotLogged()\nfortiosapi.fortiosapi.exceptions.NotLogged: Not logged on a session, please login.\n",
    "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error",
    "rc": 1,
    "_ansible_no_log": false,
    "changed": false
}
```

**Comment by greenspartan** [comment]
Hi @chillancezen,

I've tried using httpapi connection method (instead of local) but it didn't work. 
It requests for fortiosapi module :
```
fatal: [10.109.109.1]: FAILED! => {"ansible_facts": {"discovered_interpreter_python": "/usr/bin/python"}, "changed": false, "msg": "fortiosapi module is required"}
```

Morevoer, it's specified in Ansible documentation related to that module that connection local should be used.
[Ansible Documention fortios_firewall_adress module](https://docs.ansible.com/ansible/latest/modules/fortios_firewall_address_module.html)

Best regards,

**Comment by rdzielicki** [comment]
Hello,

We found the problem, it's because we didnt provided any trusted host on the Firewall, so nothing related to Ansible or FOrti module, thanks for your help.

**Comment by chillancezen** [comment]
> Hi @chillancezen,
> 
> I've tried using httpapi connection method (instead of local) but it didn't work.
> It requests for fortiosapi module :
> 
> ```
> fatal: [10.109.109.1]: FAILED! => {"ansible_facts": {"discovered_interpreter_python": "/usr/bin/python"}, "changed": false, "msg": "fortiosapi module is required"}
> ```
> 
> Morevoer, it's specified in Ansible documentation related to that module that connection local should be used.
> [Ansible Documention fortios_firewall_adress module](https://docs.ansible.com/ansible/latest/modules/fortios_firewall_address_module.html)
> 
> Best regards,

hi, you in order to use HTTPAPI, you have to unset `username` and `password`.

```
      fortios_firewall_address:
        host: "{{ host }}"
        username: "{{ username }}" <=== unset this field
        password: "{{ password }}" <==== unset this filed
        vdom: "{{ vdom }}"
        state: "present"
        ssl_verify: "no"
 
```


here is an example:
```
#cat hosts
[fortigates]
fortigate01 ansible_host=<<you fgt device address>> ansible_user="admin" ansible_password="<<your password>>"

[fortigates:vars]
ansible_network_os=fortios
```

```
#cat test.yml
- hosts: fortigates
  connection: httpapi
  vars:
   vdom: "root"
   ansible_httpapi_use_ssl: yes
   ansible_httpapi_validate_certs: no
   ansible_httpapi_port: 443
  tasks:
  - name: Configure global attributes.
    fortios_system_global:
      vdom:  "{{ vdom }}"
      system_global:
        admintimeout: "23"
        hostname: "chfdafdazzeers"
```


then
```
# ansible-playbook -i hosts test.yml
```
